(function(){
  'use strict';
  const KEY='biz_crm_service_requests_v1';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
  const save=rows=>localStorage.setItem(KEY,JSON.stringify(rows));
  const active=()=>typeof state!=='undefined'?state.activeCompany:'symetrie';
  function styles(){const s=document.createElement('style');s.textContent='.sr-shell{max-width:960px;margin:0 auto;padding:5px 16px}.sr-head{display:flex;justify-content:space-between;align-items:center;gap:8px;margin:9px 0}.sr-head strong{font-size:13px}.sr-link{border:1px solid var(--border);background:var(--surface);color:var(--text);border-radius:8px;padding:8px 10px;font-size:12px;font-weight:700;text-decoration:none}.sr-list{background:var(--surface);border:1px solid var(--border);border-radius:10px;overflow:hidden}.sr-row{display:grid;grid-template-columns:1.4fr 1fr 1fr auto;gap:10px;align-items:center;padding:10px 12px;border-top:1px solid var(--border);font-size:12px}.sr-row:first-child{border-top:0}.sr-name{font-weight:800}.sr-sub{font-size:11px;color:var(--text-soft);margin-top:2px}.sr-pill{font-size:10px;font-weight:800;padding:3px 7px;border-radius:999px;background:var(--accent-tint);color:var(--accent)}.sr-empty{padding:14px 12px;color:var(--text-soft);font-size:12px}@media(max-width:700px){.sr-row{grid-template-columns:1fr auto}.sr-row>div:nth-child(2),.sr-row>div:nth-child(3){display:none}}';document.head.appendChild(s)}
  function add(){if($('serviceRequests')||active()!=='symetrie')return;const target=$('bookingV21')||$('v2Dashboard')||document.querySelector('.toolbar');if(!target)return;const el=document.createElement('section');el.id='serviceRequests';el.className='sr-shell';target.insertAdjacentElement('afterend',el);render()}
  function render(){const el=$('serviceRequests');if(!el)return;el.style.display=active()==='symetrie'?'block':'none';const rows=load().filter(x=>x.company==='symetrie'&&!['Resolved','Closed'].includes(x.status)).slice(0,8);el.innerHTML=`<div class="sr-head"><strong>Client Care & Service Requests</strong><a class="sr-link" href="client-service.html" target="_blank" rel="noopener">Open client portal</a></div><div class="sr-list">${rows.length?rows.map(r=>`<div class="sr-row"><div><div class="sr-name">${esc(r.name||'Client')}</div><div class="sr-sub">${esc(r.requestType||'Service')} · ${esc(r.address||'No address')}</div></div><div>${esc(r.urgency||'Routine')}</div><div><span class="sr-pill">${esc(r.status||'New')}</span></div><button class="sr-link" data-service-id="${esc(r.id)}">Open</button></div>`).join(''):'<div class="sr-empty">No open service requests. New portal submissions will appear here after the secure connection is activated.</div>'}</div>`}
  function init(){if(typeof state==='undefined')return;styles();add();if(typeof setActiveCompany==='function'){const base=setActiveCompany;window.setActiveCompany=function(k){base(k);setTimeout(()=>{add();render()},0)}}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,60));else setTimeout(init,60);
})();
